version: "3.8"

services:
  # 1. RabbitMQ (The Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

  # 2. MongoDB (The Database)
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ecommerce-net

  # 3. PostgreSQL (The Command Database)
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: valury
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: postgres
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-net

  # 4. Command Service (Node.js App)
  command-service:
    build: ./command-service
    container_name: command-service
    ports:
      - "5000:5000"
    environment:
      - DB_USER=valury
      - DB_PASSWORD=your_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - ecommerce-net

  # 5. Query Service (Your Go App)
  query-service:
    build: ./query-service # Build from the Dockerfile in current directory
    container_name: query-service
    ports:
      - "8081:8081" # Map host port 8081 to container port 8081
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DB_NAME=ecommerce_read_db
      - COLLECTION_NAME=users
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - ecommerce-net

# Define a shared network so they can talk to each other
networks:
  ecommerce-net:
    driver: bridge
